name: Code quality checks

on:
  pull_request:

jobs:
  build-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Check installed versions
        run: |
          node -v

      - name: Install dependencies
        run: |
            npm install --legacy-peer-deps

      - name: Build project and Pack (PR)
        run: |
          npm run build-lib
          npm pack ./dist/common-consumption

      - name: Lint code
        run: |
          npm run lint

      - name: Run Tests
        run: |
          npm run test
